### ISSUE TITLE
Building Dataset Documentation Error

### ISSUE THREAD

**Issue by jsleep** [tensorflow/magenta#391] opened 2016-11-16 18:16 UTC
https://github.com/tensorflow/magenta/blob/master/magenta/scripts/README.md

Says to use "convert_dir_to_note_sequences" but my magenta environment only found the command "convert_**midi**_dir_to_note_sequences".

**Comment by cghawthorne** [comment] 2016-11-16 18:21
Ah sorry, that was caused by #377 that combined the musicxml and midi parser scripts and updated the documentation accordingly. We need to cut a new pip package with the new command. In the mean time, you can proceed using convert_midi_dir_to_note_sequences.

**Comment by cghawthorne** [comment] 2016-12-16 19:59
We've just released Magenta 0.1.8, so this should be fixed.

**Closed by cghawthorne** 2016-12-16 19:59 UTC

**Comment by jasondesante** [comment] 2017-09-18 08:53
now says   File "demo.py", line 16
    convert_midi_dir_to_note_sequences \
SyntaxError: can't assign to operator
