### ISSUE TITLE
bazel test error (MacOSX10.14)

### ISSUE THREAD

**Issue by oshyshkin** [tensorflow/magenta#1341] opened 2018-11-07 12:15 UTC
Hi! I have a problem when trying to test the project.

bazel: 0.18.1
Error message:

>WARNING: Processed legacy workspace file /Users/admin/magenta/tools/bazel.rc. This file will not be processed in the next release of Bazel. Please read https://github.com/bazelbuild/bazel/issues/6319 for further information, including how to upgrade.
INFO: Analysed 282 targets (0 packages loaded).
INFO: Found 226 targets and 56 test targets...
ERROR: /private/var/tmp/_bazel_admin/1176f1bbe090aa2200898e6d3db6281e/external/com_google_protobuf/BUILD:260:1: C++ compilation of rule '@com_google_protobuf//:protoc_lib' failed (Exit 1)
In file included from external/com_google_protobuf/src/google/protobuf/compiler/plugin.cc:46:
In file included from /usr/local/include/google/protobuf/compiler/plugin.pb.h:22:
In file included from /usr/local/include/google/protobuf/arena.h:52:
In file included from /usr/local/include/google/protobuf/stubs/atomic_sequence_num.h:33:
In file included from /usr/local/include/google/protobuf/stubs/atomicops.h:199:

...bunch of warning messages

>/usr/local/include/google/protobuf/stubs/atomicops_internals_macosx.h:47:9: warning: 'OSAtomicCompareAndSwap32' is deprecated: first deprecated in macOS 10.12 - Use std::atomic_compare_exchange_strong_explicit(std::memory_order_relaxed) from <atomic> instead [-Wdeprecated-declarations]
    if (OSAtomicCompareAndSwap32(old_value, new_value,
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/libkern/OSAtomicDeprecated.h:502:9: note: 'OSAtomicCompareAndSwap32' has been explicitly marked deprecated here
bool    OSAtomicCompareAndSwap32( int32_t __oldValue, int32_t __newValue, volatile int32_t *__theValue );
        ^
In file included from external/com_google_protobuf/src/google/protobuf/compiler/plugin.cc:46:
In file included from /usr/local/include/google/protobuf/compiler/plugin.pb.h:22:
In file included from /usr/local/include/google/protobuf/arena.h:52:
In file included from /usr/local/include/google/protobuf/stubs/atomic_sequence_num.h:33:
In file included from /usr/local/include/google/protobuf/stubs/atomicops.h:199:
/usr/local/include/google/protobuf/stubs/atomicops_internals_macosx.h:61:13: warning: 'OSAtomicCompareAndSwap32' is deprecated: first deprecated in macOS 10.12 - Use std::atomic_compare_exchange_strong_explicit(std::memory_order_relaxed) from <atomic> instead [-Wdeprecated-declarations]
  } while (!OSAtomicCompareAndSwap32(old_value, new_value,
            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/libkern/OSAtomicDeprecated.h:502:9: note: 'OSAtomicCompareAndSwap32' has been explicitly marked deprecated here
bool    OSAtomicCompareAndSwap32( int32_t __oldValue, int32_t __newValue, volatile int32_t *__theValue );
        ^
In file included from external/com_google_protobuf/src/google/protobuf/compiler/plugin.cc:46:
In file included from /usr/local/include/google/protobuf/compiler/plugin.pb.h:22:
In file included from /usr/local/include/google/protobuf/arena.h:52:
In file included from /usr/local/include/google/protobuf/stubs/atomic_sequence_num.h:33:
In file included from /usr/local/include/google/protobuf/stubs/atomicops.h:199:
/usr/local/include/google/protobuf/stubs/atomicops_internals_macosx.h:68:10: warning: 'OSAtomicAdd32' is deprecated: first deprecated in macOS 10.12 - Use std::atomic_fetch_add_explicit(std::memory_order_relaxed) from <atomic> instead [-Wdeprecated-declarations]
  return OSAtomicAdd32(increment, const_cast<Atomic32*>(ptr));
         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/libkern/OSAtomicDeprecated.h:146:9: note: 'OSAtomicAdd32' has been explicitly marked deprecated here
int32_t OSAtomicAdd32( int32_t __theAmount, volatile int32_t *__theValue );
        ^
In file included from external/com_google_protobuf/src/google/protobuf/compiler/plugin.cc:46:
In file included from /usr/local/include/google/protobuf/compiler/plugin.pb.h:22:
In file included from /usr/local/include/google/protobuf/arena.h:52:
In file included from /usr/local/include/google/protobuf/stubs/atomic_sequence_num.h:33:
In file included from /usr/local/include/google/protobuf/stubs/atomicops.h:199:
/usr/local/include/google/protobuf/stubs/atomicops_internals_macosx.h:73:10: warning: 'OSAtomicAdd32Barrier' is deprecated: first deprecated in macOS 10.12 - Use std::atomic_fetch_add() from <atomic> instead [-Wdeprecated-declarations]
  return OSAtomicAdd32Barrier(increment, const_cast<Atomic32*>(ptr));
         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/libkern/OSAtomicDeprecated.h:161:9: note: 'OSAtomicAdd32Barrier' has been explicitly marked deprecated here
int32_t OSAtomicAdd32Barrier( int32_t __theAmount, volatile int32_t *__theValue );
        ^
In file included from external/com_google_protobuf/src/google/protobuf/compiler/plugin.cc:46:
In file included from /usr/local/include/google/protobuf/compiler/plugin.pb.h:22:
In file included from /usr/local/include/google/protobuf/arena.h:52:
In file included from /usr/local/include/google/protobuf/stubs/atomic_sequence_num.h:33:
In file included from /usr/local/include/google/protobuf/stubs/atomicops.h:199:
/usr/local/include/google/protobuf/stubs/atomicops_internals_macosx.h:77:3: warning: 'OSMemoryBarrier' is deprecated: first deprecated in macOS 10.12 - Use std::atomic_thread_fence() from <atomic> instead [-Wdeprecated-declarations]
  OSMemoryBarrier();

...errors

>external/com_google_protobuf/src/google/protobuf/compiler/plugin.cc:66:13: error: unknown type name 'Version'
      const Version& compiler_version,
            ^
external/com_google_protobuf/src/google/protobuf/compiler/plugin.cc:94:27: error: unknown type name 'Version'
  void GetCompilerVersion(Version* version) const {
                          ^
external/com_google_protobuf/src/google/protobuf/compiler/plugin.cc:99:3: error: unknown type name 'Version'
  Version compiler_version_;
  ^
external/com_google_protobuf/src/google/protobuf/compiler/plugin.cc:128:15: error: no member named 'compiler_version' in 'google::protobuf::compiler::CodeGeneratorRequest'
      request.compiler_version(), response, parsed_files);
      ~~~~~~~ ^
external/com_google_protobuf/src/google/protobuf/compiler/plugin.cc:133:42: error: cannot initialize a parameter of type 'google::protobuf::compiler::GeneratorContext *' with an rvalue of type 'google::protobuf::compiler::GeneratorResponseContext *'
      parsed_files, request.parameter(), &context, &error);
                                         ^~~~~~~~
/usr/local/include/google/protobuf/compiler/code_generator.h:102:46: note: passing argument to parameter 'generator_context' here
                           GeneratorContext* generator_context,
                                             ^
external/com_google_protobuf/src/google/protobuf/compiler/plugin.cc:99:11: warning: private field 'compiler_version_' is not used [-Wunused-private-field]
  Version compiler_version_;
          ^
12 warnings and 5 errors generated.
INFO: Elapsed time: 2.239s, Critical Path: 1.52s
INFO: 0 processes.
FAILED: Build did NOT complete successfully


Any suggestions?

**Comment by cghawthorne** [comment] 2018-11-08 01:57
I'm not able to reproduce that error building on Mac with bazel 0.18.1-homebrew. Have you installed xcode as described in the Bazel installation instructions? https://docs.bazel.build/versions/master/install-os-x.html#step-1-install-xcode-command-line-tools

**Comment by oshyshkin** [comment] 2018-11-08 15:55
Yes, I did. I also installed bazel using brew. I also tried to re-install using the binary installer, but it didn't help. Also, I got a new bunch of errors...

>WARNING: Processed legacy workspace file /Users/admin/magenta/tools/bazel.rc. This file will not be processed in the next release of Bazel. Please read https://github.com/bazelbuild/bazel/issues/6319 for further information, including how to upgrade.
Starting local Bazel server and connecting to it...
INFO: Analysed 282 targets (56 packages loaded).
INFO: Found 226 targets and 56 test targets...
ERROR: /private/var/tmp/_bazel_admin/1176f1bbe090aa2200898e6d3db6281e/external/com_google_protobuf/BUILD:70:1: C++ compilation of rule '@com_google_protobuf//:protobuf_lite' failed (Exit 1)
In file included from external/com_google_protobuf/src/google/protobuf/implicit_weak_message.cc:31:
external/com_google_protobuf/src/google/protobuf/implicit_weak_message.h:57:41: error: allocating an object of abstract class type 'google::protobuf::internal::ImplicitWeakMessage'
  MessageLite* New() const { return new ImplicitWeakMessage; }
                                        ^
/usr/local/include/google/protobuf/message_lite.h:247:15: note: unimplemented pure virtual method 'ByteSize' in 'ImplicitWeakMessage'
  virtual int ByteSize() const = 0;
              ^
external/com_google_protobuf/src/google/protobuf/implicit_weak_message.cc:47:31: error: no template named 'ExplicitlyConstructed' in namespace 'google::protobuf::internal'
::google::protobuf::internal::ExplicitlyConstructed<ImplicitWeakMessage>
^
In file included from external/com_google_protobuf/src/google/protobuf/implicit_weak_message.cc:31:
In file included from external/com_google_protobuf/src/google/protobuf/implicit_weak_message.h:35:
/usr/local/include/google/protobuf/arena.h:252:18: error: allocating an object of abstract class type 'google::protobuf::internal::ImplicitWeakMessage'
      return new T;
                 ^
external/com_google_protobuf/src/google/protobuf/implicit_weak_message.h:59:19: note: in instantiation of function template specialization 'google::protobuf::Arena::CreateMessage<google::protobuf::internal::ImplicitWeakMessage>' requested here
    return Arena::CreateMessage<ImplicitWeakMessage>(arena);
                  ^
3 errors generated.
INFO: Elapsed time: 4.549s, Critical Path: 0.81s
INFO: 1 process: 1 local.
FAILED: Build did NOT complete successfully


Can I re-install everything from scratch somehow? It worked until I did an update to 10.14

**Comment by cghawthorne** [comment] 2018-11-08 17:57
Oh, I didn't notice your version of MacOS. I'm still on 10.13, so it's certainly possible that something in 10.14 is causing problems with the protobuf library. Can you file a bug over on the protobuf repo about it? https://github.com/protocolbuffers/protobuf

**Comment by oshyshkin** [comment] 2018-11-08 21:41
Done. I provided as many details as I knew. Please, let me know if I missed something.

**Comment by cghawthorne** [comment] 2018-11-13 19:43
Closing this issue. Will track at https://github.com/protocolbuffers/protobuf/issues/5326

**Closed by cghawthorne** 2018-11-13 19:43 UTC
