### ISSUE TITLE
CoLab MusicVAE 16 Mel Seq Reconstruction issue

### ISSUE THREAD

**Issue by Z-QIAO** [tensorflow/magenta#1734] opened 2020-05-28 21:09 UTC
Hi Adam

I am sorry to be a pain... 

In the 16-bar Melody Models, the extracted melodies would not be converted into the start or end seq reconstruction. (I tried print start_mel out and it won't match ns from the last cell) It is fine in the 2 bar mode. Thanks very much. I uploaded a video to youtube to demonstrate.

[https://youtu.be/-K9CcmfkxYU](https://youtu.be/-K9CcmfkxYU)

**Comment by adarob** [comment] 2020-05-29 13:06
This is simply a limitation of the model due to the variational bottleneck. There is a tradeoff when we train: the more we limit information flow through the bottleneck, the worse the reconstructions; the less we limit information flow, the worse the sampling.  Or if you're an optimist: the more we limit information flow through the bottleneck, the better the sampling; the less we limit information flow, the worse the reconstructions.  This tradeoff is more pronounced for longer sequences, although the hierarchical models help to overcome it somewhat vs flat models.

In some cases we have a lokl and hikl model. The lokl model has a tight bottleneck and hikl has a loose bottleneck.

**Comment by adarob** [comment] 2020-05-29 15:22
Based on the examples you sent me offline and watching the video, it does seem like there is a regression somewhere.

**Comment by adarob** [comment] 2020-05-29 15:45
It looks like there was a regression between 1.3.1 and 1.3.2.

**Comment by adarob** [comment] 2020-05-29 16:02
@iansimon https://github.com/tensorflow/magenta/commit/8899becceaa1be6267ba8971c1f578b2b55b7685 appears to be the culprit

**Comment by adarob** [comment] 2020-05-29 16:59
It looks like someone already sent in a PR for this (#1709) but it was never merged for some reason. We are merging it now and then I'll update the pip package.

**Comment by Z-QIAO** [comment] 2020-06-01 14:10
Thanks very much Adam! The only last thing is different before the meltdown is the midi download... It only downloads the mean sequence rather than the whole progression. Thanks very much!!

**Closed** 2020-06-02 15:42 UTC

**Comment by Z-QIAO** [comment] 2020-06-02 16:17
Thanks very much Adam!!! It is just so hard to search in Colab. Got it!!!
