### ISSUE TITLE
Just cannot create SequenceExamples

### ISSUE THREAD

**Issue by npuichigo** [tensorflow/magenta#158] opened 2016-08-14 09:53 UTC
When I want to create SequenceExamples from notesequences.tfrecord, message like this occurs:

`INFO:tensorflow:Processed 1 inputs total. Produced 0 outputs.`

Besides, the SequenceExample files' sizes are zero.

![qq 20160814174942](https://cloud.githubusercontent.com/assets/11533479/17648429/c15bd896-6247-11e6-84aa-2c90fafeca0a.png)

This is my notesequences.tfrecord file created from bach's Goldberg Variations:

![qq 20160814175316](https://cloud.githubusercontent.com/assets/11533479/17648437/0251fb14-6248-11e6-831c-ed8ba0322a59.png)

**Comment by prafiles** [comment] 2016-08-14 10:08
Are you sure the input sequences are not polyphonic? I'm also encountering similar issue, however if you're working on the latest pull, you'll notice that it does spit the reason out in more verbose explanations.

**Comment by npuichigo** [comment] 2016-08-14 10:45
Thanks for your reminding, but the README.md in basic_rnn says:
> This model takes monophonic melodies, meaning one note plays at a time. Use basic_rnn_create_dataset.py to extract monophonic melodies from NoteSequence protos made from your MIDI files. The script will look at each instrument track and extract a melody line if it is at least 7 measures long, and at least 5 unique pitches (with octave equivalence). If multiple notes play at the same time, one note is kept.

Does that mean polyphonic input is okay? And monophonic melodies can be extracted from original polyphonic input?

**Comment by prafiles** [comment] 2016-08-14 11:08
I've seen the "extraction mechanism" give strange outputs, to nothing. Unfortunately I'm away from my workstation, but can share the complete log with the latest pull. Both while creating the tfrecord files and then datasets?

**Comment by npuichigo** [comment] 2016-08-14 11:29
While creating the tfrecord files and datasets, messages are printed out respectively as follows:
> zhangyuchao@node1-cluster:~/tf_workspace/magenta$./dataset_processing.sh
INFO: Found 1 target...
Target //magenta/scripts:convert_midi_dir_to_note_sequences up-to-date:
  bazel-bin/magenta/scripts/convert_midi_dir_to_note_sequences
INFO: Elapsed time: 0.119s, Critical Path: 0.00s
INFO: Running command line: bazel-bin/magenta/scripts/convert_midi_dir_to_note_sequences '--midi_dir=/home/disk1/zhangyuchao/tf_workspace/magenta/midi_directory' '--output_file=/home/disk1/zhangyuchao/tf_workspace/magenta/tmp/notesequences.tfrecord' --recursive
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
INFO:tensorflow:Converting MIDI files in '/home/disk1/zhangyuchao/tf_workspace/magenta/midi_directory/'.
INFO:tensorflow:Converted 1 MIDI files in '/home/disk1/zhangyuchao/tf_workspace/magenta/midi_directory/'.
INFO:tensorflow:Could not parse 0 MIDI files.

> zhangyuchao@node1-cluster:~/tf_workspace/magenta$ ./attention_rnn_create_dataset.sh
INFO: Found 1 target...
Target //magenta/models/attention_rnn:attention_rnn_create_dataset up-to-date:
  bazel-bin/magenta/models/attention_rnn/attention_rnn_create_dataset
INFO: Elapsed time: 0.103s, Critical Path: 0.00s
INFO: Running command line: bazel-bin/magenta/models/attention_rnn/attention_rnn_create_dataset '--input=/home/disk1/zhangyuchao/tf_workspace/magenta/tmp/notesequences.tfrecord' '--output_dir=/home/disk1/zhangyuchao/tf_workspace/magenta/tmp/attention_rnn/sequence_examples' '--eval_ratio=0.10'
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
INFO:tensorflow:
Completed.
INFO:tensorflow:Processed 1 inputs total. Produced 0 outputs.

Maybe you can try these two MIDI files of mine.
[MIDI.zip](https://github.com/tensorflow/magenta/files/417001/MIDI.zip)

Thanks a lot!

**Comment by cghawthorne** [comment] 2016-08-30 19:15
@danabo do you know what's happening with the input pipeline here?

**Comment by danabo** [comment] 2016-08-30 19:41
npuichigo, both mid files you shared contain multiple time signatures. The Bach piece switches time sig frequently. The HP piece has a 4/4 and 6/8 time sig both at time zero for some reason. Since some models use information about where notes are in the bar, we wanted to avoid complicating things and we discard MIDIs with multiple time signatures.

I'll add a message that counts how many samples are discarded because of multiple time signatures so this is clear in the future. Sorry for the inconvenience.

**Comment by danabo** [comment] 2016-08-30 19:52
When I ran the melody extractor with my change over your mid files I got this output:
INFO:tensorflow:Processed 2 inputs total. Produced 0 outputs.
INFO:tensorflow:DAGPipeline_Quantizer_sequences_discarded_because_multiple_time_signatures: 2

The reason for discarding the sequences is now displayed.

**Comment by danabo** [comment] 2016-08-30 20:13
I'm closing this since things are working as intended.

**Closed by danabo** 2016-08-30 20:13 UTC

**Comment by npuzhangyuchao** [comment] 2016-08-31 02:13
Thank you for your reply! It's very helpful to me, and I'll try another piece.
