### ISSUE TITLE
basic_rnn, getting started

### ISSUE THREAD

**Issue by vmeade** [tensorflow/magenta#264] opened 2016-10-07 19:48 UTC
**Here is the code I ran:**

docker run -it -p 6006:6006 -v /c/Users/Vincent/notebooks:/magenta-data tensorflow/magenta

bazel run //magenta/models/basic_rnn:basic_rnn_generate -- \
--bundle_file=/magenta-models/basic_rnn.mag \
--output_dir=/magenta-data \
--num_outputs=10 \
--num_steps=128 \
--primer_melody="[60]"

**And I get this:**
INFO:tensorflow:Wrote 10 MIDI files to /tmp/melody_rnn/generated

I'm not on Mac, so the /tmp/ directory doesn't exist. I didn't specify this path. Could this be written somewhere into the bundle_file, or is this path being generated somewhere else?

**Comment by x267wu** [comment] 2016-10-07 21:12
You can open the /tmp folder on a Mac by typing `open /tmp` in the terminal
hope that helps!

**Comment by vmeade** [comment] 2016-10-08 21:01
@x267wu 
Thanks, I'm on Windows. I'll look at the code when I have time and see if i can figure out why the path gets written to /tmp/, I'm sure it's within the bundle_file. It's the only place where there could be this variation. Plus I think magenta was intended through it's stack to primarily run on apple computers so it would make sense the programs would utilize a standard feature of the apple operating system.

**Comment by cghawthorne** [comment] 2016-10-11 18:42
@vmeade I'm having trouble reproducing this problem. Can you paste the full output of that command?  In particular, I'm interested in what Bazel says for the "Running command line" output. Here's what it looks like for me:

```
# bazel run //magenta/models/basic_rnn:basic_rnn_generate -- \
> --bundle_file=/magenta-models/basic_rnn.mag \
> --output_dir=/magenta-data \
> --num_outputs=10 \
> --num_steps=128 \
> --primer_melody="[60]"
INFO: Reading 'startup' options from /root/.bazelrc: --batch
WARNING: /root/.cache/bazel/_bazel_root/cb5f479c6a7afa91f510d7ce625f6aa5/external/protobuf/WORKSPACE:1: Workspace name in /root/.cache/bazel/_bazel_root/cb5f479c6a7afa91f510d7ce625f6aa5/external/protobuf/WORKSPACE (@__main__) does not match the name given in the repository's definition (@protobuf); this will cause a build error in future versions.
INFO: Found 1 target...
Target //magenta/models/basic_rnn:basic_rnn_generate up-to-date:
  bazel-bin/magenta/models/basic_rnn/basic_rnn_generate
INFO: Elapsed time: 3.384s, Critical Path: 0.39s

INFO: Running command line: bazel-bin/magenta/models/basic_rnn/basic_rnn_generate '--bundle_file=/magenta-models/basic_rnn.mag' '--output_dir=/magenta-data' '--num_outputs=10' '--num_steps=128' '--primer_melody=[60]'
INFO:tensorflow:Wrote 10 MIDI files to /magenta-data

```

**Comment by vmeade** [comment] 2016-10-21 03:27
@cghawthorne 

Yes, I would love to do this either tomorrow or Saturday. ( I just got a new job and lost a lot of time to freely program :grinning: )

I can replicate the full output then. 

Ya, I'm wondering if my theory was right. I would be proud if I could guess that bit. :+1:

**Comment by cghawthorne** [comment] 2016-11-10 00:31
Closing due to lack of updates. Please reopen if you're still having problems.

**Closed by cghawthorne** 2016-11-10 00:31 UTC
